version: '3.4'

# 共通定義のテンプレート化
x-template: &template
  build:
    context: .
  volumes:
    - ./working:/opt/program/working:cached
    - ~/.kaggle:/root/.kaggle:cached
    - /Users/takapy/python/repository/geek_blog:/opt/program/working/geek_blog:cached

services:
  ml-jupyter:
    container_name: 'ml-jupyter'
    image: ml-jupyter:latest
    user: root
    ports:
      - "8900:8900" # for jupyter
      - "6006:6006" # for tensorboard
      - "8082:8082" # for Luigi
    command: jupyter lab --allow-root
    <<: *template
